const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const input=process.argv[2]||require('node:path').join(__dirname,'../index.html');
const script=fs.readFileSync(input,'utf8').split('<script>')[1].split('</script>')[0].replace(/boot\(\);\s*$/,'');
const node={addEventListener(){},querySelector(){return node},querySelectorAll(){return []},classList:{toggle(){}},style:{}};
const context=vm.createContext({window:{addEventListener(){}},document:{querySelector(){return node},querySelectorAll(){return []}},setInterval(){},setTimeout(){},clearTimeout(){},Date,Intl,URL,location:new URL('https://chief-of-staff-v3-live.vercel.app/'),console,confirm:()=>true});
vm.runInContext(script,context);
const run=code=>vm.runInContext(code,context);
(async()=>{
  run(`S.areas=[{key:'work',title:'Работа'}];S.projects=[{id:'p1',title:'Old',status:'active',risk_level:'green'}];S.project=S.projects[0];`);
  const form=values=>({elements:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,{value:v}]))});
  context.form=form({title:'  New project  ',status:'paused',area_key:'work',risk_level:'yellow'});
  assert.deepEqual(JSON.parse(JSON.stringify(run('projectEditPayload(form)'))),{title:'New project',status:'paused',area_key:'work',risk_level:'yellow'});
  context.form=form({title:' ',status:'active',area_key:'work',risk_level:'green'});assert.throws(()=>run('projectEditPayload(form)'),/название/);
  context.form=form({title:'New',status:'active',area_key:'missing',risk_level:'green'});assert.throws(()=>run('projectEditPayload(form)'),/сферу/);
  context.form=form({title:'New',status:'active',area_key:'',risk_level:'green'});assert.equal(run('projectEditPayload(form).area_key'),null);
  run(`var requests=[];api=async(path,options)=>{requests.push({path,options});return []};`);
  await assert.rejects(run(`persistProjectChanges('p1',{title:'Not saved'})`),/не подтверждены/);
  assert.equal(run('S.projects[0].title'),'Old');
  run(`api=async(path,options)=>{requests.push({path,options});return [{id:'p1',...options.body}]};`);
  await run(`persistProjectChanges('p1',{title:'Confirmed',status:'paused'})`);
  assert.equal(run('S.projects[0].title'),'Confirmed');assert.equal(run('S.project.status'),'paused');
  assert.equal(run('requests.at(-1).path'),'/rest/v1/projects?id=eq.p1');assert.equal(run('requests.at(-1).options.prefer'),'return=representation');
  run(`S.tasks=[{id:'t1',status:'open'},{id:'t2',status:'completed'}];var now=Date.now();var recent={id:'e1',commitment_id:'t1',source:'timer',started_at:new Date(now-3600000).toISOString(),ended_at:null};var stale={...recent,id:'e2',started_at:new Date(now-13*3600000).toISOString()};var completed={...recent,id:'e3',commitment_id:'t2'};var historical={...stale,id:'e4',ended_at:new Date(now).toISOString()};S.time=[recent,stale,completed,historical];`);
  assert.equal(run('timerNeedsReview(recent,now)'),false);assert.equal(run('timerNeedsReview(stale,now)'),true);assert.equal(run('timerNeedsReview(completed,now)'),true);assert.equal(run('timerNeedsReview(historical,now)'),false);
  assert.ok(run('taskSeconds("t1")')>=14*3600&&run('taskSeconds("t1")')<14*3600+3);assert.equal(run('taskSeconds("t2")'),0);assert.equal(run('stale.ended_at'),null);assert.equal(run('completed.ended_at'),null);
  run('S.time=[completed]');const banner=run('timerBannerHtml()');assert.match(banner,/Проверьте незавершённый таймер/);assert.doesNotMatch(banner,/● Таймер идёт/);assert.match(banner,/Уточнить и остановить/);
  run(`requests=[];api=async(path,options)=>{requests.push({path,options});return []};`);
  await assert.rejects(run(`persistTimerEnd(recent,new Date(now+3600000).toISOString())`),/будущем/);
  await assert.rejects(run(`persistTimerEnd(recent,new Date(now-7200000).toISOString())`),/раньше/);assert.equal(run('requests.length'),0);
  await assert.rejects(run(`persistTimerEnd(recent,new Date(now).toISOString())`),/не подтвердил/);assert.equal(run('recent.ended_at'),null);
  run(`api=async(path,options)=>{requests.push({path,options});return [{id:'e2',...options.body}]};`);
  await run(`persistTimerEnd(stale,new Date(now-12*3600000).toISOString())`);assert.equal(run('entrySeconds(stale)'),3600);assert.equal(run('timerNeedsReview(stale)'),false);assert.match(run('requests.at(-1).path'),/ended_at=is.null/);
  run(`S.time=[completed];requests=[];toast=()=>{};render=()=>{};reviewTimer=async()=>false;api=async(path,options)=>{requests.push({path,options});throw Error('Network')};`);
  await run(`startTimer('t1')`);assert.equal(run('requests.length'),0,'Cancel stale timer review must block new timer');
  run(`S.time=[recent];requests=[];`);await run(`startTimer('t2')`);assert.equal(run('requests.length'),1);assert.equal(run('requests[0].options.method'),'PATCH','Failed stop must not start second timer');
  console.log('PASS: project edit payload, rejected/confirmed persistence, stale/completed timer display, fact exclusion, historical preservation, timer validation, failed/cancelled stop blocks new timer');
})().catch(e=>{console.error(e);process.exitCode=1});
